### ISSUE TITLE
Object #<Assemble> has no method 'namespace'

### ISSUE THREAD

**Issue by jerome-toole** [assemble/gulp-assemble#14]
Strange problem has suddenly popped up for me when I specify data options.

my options look like this:
```javascript
var options = {
    data: 'data/*/**.{json,yml}',
    partials: ['data/partials/*.md', '*.hbs'],
    layoutdir: '*.hbs',
};
```

whenever I run gulp assemble, I get an error saying:
```
TypeError: Object #<Assemble> has no method 'namespace' at Object.module.exports (C:\xampp\x\node_modules\gulp-assemble\index.js:28:27)
at Gulp.gulp.task.server.listen.gulp.watch.server.changed.body.files (C:\xampp\x\gulpfile.js:75:23)
at module.exports (C:\xampp\x\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
at Gulp.Orchestrator._runTask (C:\xampp\x\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
at Gulp.Orchestrator._runStep (C:\xampp\x\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
at Gulp.Orchestrator.start (C:\xampp\x\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
at C:\Users\New User\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:121:20
at process._tickCallback (node.js:419:13)
at Function.Module.runMain (module.js:499:11)
at startup (node.js:119:16)
```

if I remove the line:
```javascript
data: 'data/*/**.{json,yml}',
```
the error doesn't show but of course my data doesn't get pulled in. 

If I remove this line from index.js:
```
  if (opts.data) assemble.namespace(':basename', opts.data);
```
then again assemble completes but my data isn't compiled.

I've tried reinstalling the node-modules and node/npm.

**Comment by doowb** [comment]
Try with the newer versions. If this is still an issue, please reopen.
