### ISSUE TITLE
Error: The partial alert.hbs could not be found

### ISSUE THREAD

**Issue by pburtchaell** [assemble/gulp-assemble#17]
I have been having an issue on several projects that use gulp-assemble. It where it will return the error `The partial <partialname>.hbs can not be found` when compiling any page that has a partial. 

To make sure it was not my code, I ran the test in gulp-assemble repository with a partial and get the same error. Here it is: 

```
[15:51:44] Using gulpfile ~/.repositories/.assemble/gulp-assemble/gulpfile.js
[15:51:44] Starting 'assemble'...
[15:51:44] Finished 'assemble' after 93 ms

/Users/patrick/.repositories/.assemble/gulp-assemble/node_modules/assemble/node_modules/assemble-utils/node_modules/session-cache/node_modules/continuation-local-storage/context.js:78
      throw exception;
            ^
Error: The partial alert.hbs could not be found
    at new Error (<anonymous>)
    at Error.Exception (/Users/patrick/.repositories/.assemble/gulp-assemble/node_modules/assemble/node_modules/engine-assemble/node_modules/engine-handlebars/node_modules/handlebars/dist/cjs/handlebars/exception.js:13:41)
    at Object.invokePartial (/Users/patrick/.repositories/.assemble/gulp-assemble/node_modules/assemble/node_modules/engine-assemble/node_modules/engine-handlebars/node_modules/handlebars/dist/cjs/handlebars/runtime.js:179:11)
    at Object.invokePartialWrapper [as invokePartial] (/Users/patrick/.repositories/.assemble/gulp-assemble/node_modules/assemble/node_modules/engine-assemble/node_modules/engine-handlebars/node_modules/handlebars/dist/cjs/handlebars/runtime.js:46:39)
    at Object.eval (eval at <anonymous> (/Users/patrick/.repositories/.assemble/gulp-assemble/node_modules/assemble/node_modules/engine-assemble/node_modules/engine-handlebars/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:171:23), <anonymous>:5:17)
    at ret (/Users/patrick/.repositories/.assemble/gulp-assemble/node_modules/assemble/node_modules/engine-assemble/node_modules/engine-handlebars/node_modules/handlebars/dist/cjs/handlebars/runtime.js:137:30)
    at ret (/Users/patrick/.repositories/.assemble/gulp-assemble/node_modules/assemble/node_modules/engine-assemble/node_modules/engine-handlebars/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:422:21)
    at Object.engine.render (/Users/patrick/.repositories/.assemble/gulp-assemble/node_modules/assemble/node_modules/template/node_modules/engine-cache/index.js:173:37)
    at Assemble.Template.renderAsync (/Users/patrick/.repositories/.assemble/gulp-assemble/node_modules/assemble/node_modules/template/index.js:2025:12)
    at Assemble.Template.renderBase (/Users/patrick/.repositories/.assemble/gulp-assemble/node_modules/assemble/node_modules/template/index.js:1897:15)
```

**Comment by doowb** [comment]
This should be fixed. Please reopen if it's still an issue.
