### ISSUE TITLE
Problem With fs.js?

### ISSUE THREAD

**Issue by johjacb** [assemble/gulp-assemble#23]
I've got this setup: 
 ```
assemble.data({site: {title: 'Site Title'}});
assemble.data(['test/fixtures/data/*.{json,yml}']);
assemble.layouts(['./src/templates/layouts/']);
assemble.partials(['./src/templates/partials/*.hbs']);

gulp.task('assemble', function(){
	gulp.src('./src/templates/pages/*.hbs')
		.pipe(gulpAssemble(assemble))
		.pipe(gulp.dest(outputDir + ''))
		.pipe(reload({stream:true}));
})
```

When I run 'gulp assemble', I see this output:

```
fs.js:554
  var r = binding.read(fd, buffer, offset, length, position);
                  ^
Error: EISDIR, illegal operation on a directory
    at Error (native)
    at Object.fs.readSync (fs.js:554:19)
    at Object.fs.readFileSync (fs.js:386:28)
    at Object.Loader.readFn [as read] (/Users/awake/Sites/fizz/node_modules/assemble/node_modules/template/node_modules/load-templates/index.js:110:13)
    at read (/Users/awake/Sites/fizz/node_modules/assemble/node_modules/template/node_modules/load-templates/node_modules/map-files/index.js:53:20)
    at /Users/awake/Sites/fizz/node_modules/assemble/node_modules/template/node_modules/load-templates/node_modules/map-files/index.js:28:15
    at Array.reduce (native)
    at mapFiles (/Users/awake/Sites/fizz/node_modules/assemble/node_modules/template/node_modules/load-templates/node_modules/map-files/index.js:25:16)
    at Loader.mapFiles (/Users/awake/Sites/fizz/node_modules/assemble/node_modules/template/node_modules/load-templates/index.js:131:10)
    at Loader.parseFiles (/Users/awake/Sites/fizz/node_modules/assemble/node_modules/template/node_modules/load-templates/index.js:176:20)
    at Loader.normalizeFiles (/Users/awake/Sites/fizz/node_modules/assemble/node_modules/template/node_modules/load-templates/index.js:215:20)
    at Loader.normalizeString (/Users/awake/Sites/fizz/node_modules/assemble/node_modules/template/node_modules/load-templates/index.js:284:18)
    at Loader._format (/Users/awake/Sites/fizz/node_modules/assemble/node_modules/template/node_modules/load-templates/index.js:499:35)
    at Loader.load (/Users/awake/Sites/fizz/node_modules/assemble/node_modules/template/node_modules/load-templates/index.js:522:27)
    at /Users/awake/Sites/fizz/node_modules/assemble/node_modules/template/lib/loaders/templates.js:15:24
    at /Users/awake/Sites/fizz/node_modules/assemble/node_modules/template/node_modules/loader-cache/index.js:196:12
```

I just updated to latest node, gulp, gulp-assemble, assemble. Did a clean/reinstall of node_modules.

Am I missing something easy?

Thanks!

**Comment by doowb** [comment]
> `assemble.layouts(['./src/templates/layouts/']);`

Make this a glob pattern too.

**Comment by johjacb** [comment]
Awesome - knew it was something simple. Thanks for the speedy reply.

However, now I'm seeing this error:
```
TypeError: Cannot assign to read only property 'src' of layout:default.hbs
```

Thanks

**Comment by doowb** [comment]
Will you open this in the [assemble issues](https://github.com/assemble/assemble/issues) since these probably aren't `gulp-assemble` issues. Example repos with the error are helpful too.

**Comment by jonschlinkert** [comment]
related to https://github.com/assemble/assemble/issues/669#issuecomment-83019436

**Comment by jonschlinkert** [comment]
@johjacb just carrying over the convo from the other issue...  we might just need to bump the version https://github.com/assemble/gulp-assemble/blob/master/package.json#L38

**Comment by doowb** [comment]
That's a `devDependency` and that branch is gone now, so we should be updating it anyway.

**Comment by jonschlinkert** [comment]
@johjacb try clearing everything and reinstalling from scratch

**Comment by doowb** [comment]
@johjacb one thing I noticed is that you have the extension when describing the layout to use. Update the frontmatter to `layout: default`.

But the error you're describing is coming from a middleware (probably an `onLoad` middleware, but I'm not sure)

**Comment by johjacb** [comment]
Hi - thanks for your time on this I greatly appreciate it. I cleared out everything and reinstalled, updated to 0.6.0-beta.3. Changed to layout: default. 

I no longer get the above errors, but I do get a new one: 
```
/Users/awake/Sites/fizz/node_modules/gulp-assemble/node_modules/template-render/node_modules/gulp-util/lib/PluginError.js:102
    return '    ' + prop + ': ' + self[prop];
                                ^
TypeError: Cannot convert object to primitive value
    at stringifyProperty (/Users/awake/Sites/fizz/node_modules/gulp-assemble/node_modules/template-render/node_modules/gulp-util/lib/PluginError.js:102:33)
    at Array.map (native)
    at PluginError._messageDetails (/Users/awake/Sites/fizz/node_modules/gulp-assemble/node_modules/template-render/node_modules/gulp-util/lib/PluginError.js:101:27)
    at PluginError._messageWithDetails (/Users/awake/Sites/fizz/node_modules/gulp-assemble/node_modules/template-render/node_modules/gulp-util/lib/PluginError.js:80:22)
    at PluginError.toString (/Users/awake/Sites/fizz/node_modules/gulp-assemble/node_modules/template-render/node_modules/gulp-util/lib/PluginError.js:124:16)
    at DestroyableTransform.<anonymous> (/Users/awake/Sites/fizz/node_modules/assemble/node_modules/assemble-utils/node_modules/session-cache/node_modules/continuation-local-storage/context.js:78:13)
    at DestroyableTransform.emit (events.js:104:17)
    at DestroyableTransform.emitted [as emit] (/Users/awake/Sites/fizz/node_modules/assemble/node_modules/assemble-utils/node_modules/session-cache/node_modules/continuation-local-storage/node_modules/emitter-listener/listener.js:122:21)
    at emitReadable_ (/Users/awake/Sites/fizz/node_modules/gulp-assemble/node_modules/template-init/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/Users/awake/Sites/fizz/node_modules/gulp-assemble/node_modules/template-init/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/Users/awake/Sites/fizz/node_modules/gulp-assemble/node_modules/template-init/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (/Users/awake/Sites/fizz/node_modules/gulp-assemble/node_modules/template-init/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (/Users/awake/Sites/fizz/node_modules/gulp-assemble/node_modules/template-init/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at Object.pushToStream (/Users/awake/Sites/fizz/node_modules/gulp-assemble/node_modules/template-init/node_modules/template-utils/lib/utils/pushToStream.js:20:12)
    at DestroyableTransform._flush (/Users/awake/Sites/fizz/node_modules/gulp-assemble/node_modules/template-init/index.js:65:14)
    at DestroyableTransform.<anonymous> (/Users/awake/Sites/fizz/node_modules/gulp-assemble/node_modules/template-init/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12)
```

Again - thanks for your help!

**Comment by jonschlinkert** [comment]
can you copy the latest contents of your gulpfile here?

**Comment by johjacb** [comment]
alright I got it! I was using ```{{> body }}``` to pull in my pages. Changing to ```{% body %}``` solved the issue and everything is working as expected!

**Comment by jonschlinkert** [comment]
ah, good deal. glad we got it solved!
