### ISSUE TITLE
assemble dependency not found

### ISSUE THREAD

**Issue by stephenway** [assemble/gulp-assemble#34]
Unfortunately I'm unable to get gulp to recognize that assemble is present in gulp-assemble

``` js
# gulpfile.js
'use strict';
var gulp = require('gulp');
var assemble = require('assemble');
var gulpAssemble = require('gulp-assemble');

gulp.task('assemble', function() {
  gulp.src('./docs/**/*.hbs')
    .pipe(gulpAssemble(assemble))
    .pipe(gulp.dest('_gh_pages/'));
});
```

``` shell
$ gulp watch
module.js:338
    throw err;
          ^
Error: Cannot find module 'assemble'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/stephen/code/actual/framework/gulpfile.js:6:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

$ ls node_modules/gulp-assemble/node_modules/
assemble        fixture         gulp-extname    gulp-util       template-render
event-stream    gulp            gulp-htmlmin    template-init
```

**Comment by doowb** [comment]
`assemble` is only a devDependency for `gulp-assemble` used for testing and examples. If you're using `gulp-assemble` in another project, then you'll need to also do `npm i assemble@beta -D` to add it to your project's devDependencies. We're doing it this way to allow you to use the instance and version of assemble that you want to use.
